theme: jekyll-theme-cayman
title: 周鬼才's blog
SEOTitle: 老街 | tingsven's blog
email: tingsven@163.com
description: "What is the Purpose of LIFE."
keyword: "tingsven 周子博 博客 Python Android IOS"
url: "https://7ippo.github.io/"