theme: jekyll-theme-cayman
title: 周鬼才's personal blog
SEOTitle: 老街 | tingsven's blog
email: tingsven@163.com
description: "To see the world, things dangerous to come to,
To see behind walls, to draw closer,
To find each other and to feel
That is the Purpose of LIFE."
keyword: "tingsven 周子博 博客 Python Android IOS"
url: "https://7ippo.github.io/"